name: PracticaGitHubActions

on:
  push:
    branches:
      - main

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  cypress_job:
    needs: linter_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start server and run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
        continue-on-error: true
        id: cypress
          # start: npm run dev
          # wait-on: http://localhost:3000
          # wait-on-timeout: 120
          # record: false
          # browser: electron

      - name: Save Cypress results
        run: echo "Success" > result.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: result.txt
