name: PracticaGitHubActions

on:
  push:
    branches:
      - main

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  cypress_job:
    needs: linter_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Start server and run Cypress tests
        run: |
          npm start & # Inicia el servidor en segundo plano
          npx wait-on http://localhost:3000 # Espera a que el servidor esté listo
          npx cypress run > result.txt # Ejecuta Cypress y guarda el resultado en result.txt
        continue-on-error: true

      - name: Display test results
        run: cat result.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: result.txt
